-- ============================================================================
-- Annual-accounts document store.
--
-- We persist the original NBB-delivered PDFs in Supabase Storage so that:
--   1. We can show the original document to the user (audit trail).
--   2. We don't have to re-download from NBB if the extraction pipeline is
--      re-run.
--   3. The salesperson can attach the PDF to outreach if needed.
--
-- Bucket is private (not public); reads go through short-lived signed
-- URLs generated by the service-role client.
-- ============================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('annual-accounts', 'annual-accounts', false)
ON CONFLICT (id) DO NOTHING;

-- Track the storage object path on filing_references so we can map
-- back from a filing → its PDF without scanning the bucket. Path
-- convention: '{enterprise_number}/{reference}.pdf'.
ALTER TABLE public.filing_references
    ADD COLUMN IF NOT EXISTS storage_path text;
