import { Calculator, Droplets, TrendingUp, Wallet } from "lucide-react";

import { cn } from "@/lib/cn";

/**
 * Annexe — formula reference page. Lists every computed ratio with its
 * definition, what it tells the reader, and any caveats from the
 * underlying NBB filings (most relevant: the cash-flow approximations
 * and the missing-inventory rule for the quick ratio).
 *
 * Designed to be linked from the small ? icon on each ratio card and
 * from the sidebar — pure static content, no client interactivity.
 */
export default function AnnexePage() {
  return (
    <div className="mx-auto flex max-w-4xl flex-col gap-6">
      <header>
        <div className="mb-1 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-widest text-ink-muted">
          <Calculator className="h-3.5 w-3.5" />
          Annexe
        </div>
        <h1 className="text-2xl font-bold text-ink">
          Financial ratio formulas
        </h1>
        <p className="mt-1 text-sm text-ink-subtle">
          Every number on the company detail page comes from one of these
          formulas, applied to fields extracted from the NBB filing. The
          source NBB heading codes are listed in italic where relevant.
        </p>
      </header>

      <Group
        title="Profitability & Growth"
        caption="Margins are dimensionless ratios — values close to 0 are
        thin, around 0.10–0.20 are healthy for most industries."
        formulas={PROFITABILITY}
        icon={TrendingUp}
        accent="emerald"
      />

      <Group
        title="Cash flow (approximations)"
        caption="Belgian filings don't publish a mandatory cash-flow
        statement. We reconstruct CFO and FCF from the income statement
        and the change in fixed assets. Both are flagged with `~` on the
        company detail page."
        formulas={CASH_FLOW}
        icon={Wallet}
        accent="violet"
      />

      <Group
        title="Liquidity & Solvency"
        caption="Ratios under 1 indicate the company may struggle to meet
        short-term obligations; over 2 is generally considered safe."
        formulas={LIQUIDITY}
        icon={Droplets}
        accent="blue"
      />

      <Sources />
    </div>
  );
}

type FormulaRow = {
  label: string;
  formula: string;
  meaning: string;
  inputs: string;
  caveat?: string;
};

const PROFITABILITY: FormulaRow[] = [
  {
    label: "Revenue growth",
    formula: "(Revenue − Prev. Revenue) ÷ |Prev. Revenue|",
    meaning:
      "Year-on-year change in turnover. Negative means the company shrank.",
    inputs: "NBB code 70 across two consecutive filings.",
    caveat:
      "Empty when the company has only one filing on record yet.",
  },
  {
    label: "Operating margin",
    formula: "Operating Profit ÷ Revenue",
    meaning:
      "Profit left after operating costs, before interest and tax. Industry-dependent.",
    inputs: "NBB code 9901 ÷ NBB code 70.",
  },
  {
    label: "Net margin",
    formula: "Net Profit ÷ Revenue",
    meaning:
      "Final profit after every cost (operating, financial, tax, exceptional).",
    inputs: "NBB code 9904 ÷ NBB code 70.",
  },
  {
    label: "Return on equity (ROE)",
    formula: "Net Profit ÷ Total Equity",
    meaning:
      "How efficiently the company turns shareholder equity into profit.",
    inputs: "NBB code 9904 ÷ NBB code 10/15.",
  },
];

const CASH_FLOW: FormulaRow[] = [
  {
    label: "Operating cash flow (~)",
    formula: "Net Profit + Depreciation",
    meaning:
      "Cash generated by day-to-day operations. A simplified version of CFO using only the income-statement items the NBB filing exposes.",
    inputs: "NBB code 9904 + NBB code 630.",
    caveat:
      "Abbreviated schemas often don't break out depreciation; in that case we fall back to Net Profit alone, which underestimates CFO.",
  },
  {
    label: "CapEx (~)",
    formula: "ΔFixed Assets + Depreciation",
    meaning:
      "Estimated capital expenditure. Derived from the change in fixed assets between two consecutive filings plus the period's depreciation.",
    inputs:
      "NBB code 20/28 (current − previous) + NBB code 630 (current).",
    caveat: "Needs two consecutive filings.",
  },
  {
    label: "Free cash flow (~)",
    formula: "Op. cash flow (~) − CapEx (~)",
    meaning:
      "Cash available after maintaining the productive capital base. Negative = the business is consuming more cash than it produces.",
    inputs: "Both approximations above.",
    caveat:
      "Empty when no prior filing exists (CapEx can't be derived).",
  },
];

const LIQUIDITY: FormulaRow[] = [
  {
    label: "Current ratio",
    formula: "Current Assets ÷ Short-term Debt",
    meaning:
      "Can the company pay its short-term debts using its short-term assets? ≥ 1 means yes.",
    inputs: "NBB code 29/58 ÷ NBB code 42/48.",
  },
  {
    label: "Quick ratio",
    formula: "(Current Assets − Inventory) ÷ Short-term Debt",
    meaning:
      "Same idea as current ratio, but excluding inventory (which can't always be liquidated quickly).",
    inputs: "(NBB code 29/58 − NBB code 3) ÷ NBB code 42/48.",
    caveat:
      "When the filing has no inventory line — common on abbreviated schemas for service companies — we treat inventory as zero, which makes the quick ratio equal to the current ratio.",
  },
  {
    label: "Cash ratio",
    formula: "Cash & Equivalents ÷ Short-term Debt",
    meaning: "Most conservative liquidity test: only counts cash on hand.",
    inputs: "NBB code 54/58 ÷ NBB code 42/48.",
  },
  {
    label: "Debt / Equity",
    formula: "(Long-term Debt + Short-term Debt) ÷ Total Equity",
    meaning:
      "Leverage ratio. High means the company is financed mostly by debt; low means mostly by equity.",
    inputs:
      "(NBB code 17 + NBB code 42/48) ÷ NBB code 10/15. If both legs are missing, falls back to Total Liabilities ÷ Equity.",
  },
  {
    label: "Equity ratio",
    formula: "Total Equity ÷ Total Assets",
    meaning:
      "Solvency cushion. The share of the asset base funded by shareholders rather than creditors.",
    inputs: "NBB code 10/15 ÷ NBB code 20/58.",
  },
];

type GroupAccent = "emerald" | "violet" | "blue";

const GROUP_PALETTE: Record<
  GroupAccent,
  { iconBg: string; iconFg: string; border: string; codeBg: string; codeFg: string }
> = {
  emerald: {
    iconBg: "bg-accent-profit-50",
    iconFg: "text-accent-profit-700",
    border: "border-accent-profit-600/30",
    codeBg: "bg-accent-profit-50",
    codeFg: "text-accent-profit-700",
  },
  violet: {
    iconBg: "bg-accent-equity-50",
    iconFg: "text-accent-equity-700",
    border: "border-accent-equity-600/30",
    codeBg: "bg-accent-equity-50",
    codeFg: "text-accent-equity-700",
  },
  blue: {
    iconBg: "bg-accent-cash-50",
    iconFg: "text-accent-cash-700",
    border: "border-accent-cash-600/30",
    codeBg: "bg-accent-cash-50",
    codeFg: "text-accent-cash-700",
  },
};

function Group({
  title,
  caption,
  formulas,
  icon: Icon,
  accent,
}: {
  title: string;
  caption: string;
  formulas: FormulaRow[];
  icon: React.ElementType;
  accent: GroupAccent;
}) {
  const palette = GROUP_PALETTE[accent];
  return (
    <section className="rounded-card bg-surface p-6 shadow-card ring-1 ring-surface-line">
      <header className="mb-4 flex items-start gap-3">
        <span
          className={cn(
            "grid h-10 w-10 shrink-0 place-items-center rounded-xl",
            palette.iconBg
          )}
        >
          <Icon className={cn("h-5 w-5", palette.iconFg)} />
        </span>
        <div>
          <h2 className="text-base font-semibold text-ink">{title}</h2>
          <p className="mt-0.5 text-xs text-ink-muted">{caption}</p>
        </div>
      </header>

      <ul className="flex flex-col gap-5">
        {formulas.map((row) => (
          <li
            key={row.label}
            className={cn("border-l-2 pl-4", palette.border)}
          >
            <div className="flex flex-wrap items-baseline justify-between gap-3">
              <h3 className="text-sm font-semibold text-ink">{row.label}</h3>
              <code
                className={cn(
                  "rounded-md px-2 py-1 font-mono text-[12px] font-medium",
                  palette.codeBg,
                  palette.codeFg
                )}
              >
                {row.formula}
              </code>
            </div>
            <p className="mt-1 text-sm text-ink-subtle">{row.meaning}</p>
            <p className="mt-1 text-[11px] italic text-ink-muted">
              {row.inputs}
            </p>
            {row.caveat && (
              <p className="mt-1 text-[11px] text-amber-700">
                Note — {row.caveat}
              </p>
            )}
          </li>
        ))}
      </ul>
    </section>
  );
}

function Sources() {
  return (
    <section className="rounded-card bg-surface-sub p-6 ring-1 ring-surface-line">
      <h2 className="mb-2 text-sm font-semibold text-ink">
        Where the numbers come from
      </h2>
      <p className="text-xs leading-relaxed text-ink-subtle">
        The raw values are extracted from filings deposited with the
        Belgian Central Balance Sheet Office (CBSO). The NBB heading
        codes above (e.g. <code>70</code>, <code>20/58</code>,{" "}
        <code>9904</code>) follow the standardised Belgian-GAAP chart of
        accounts. For full-schema and non-profit filings deposited from
        2007 onwards we read the XBRL representation directly; for
        older or dimensional filings we fall back to an LLM extractor
        parsing the PDF text. The <code>source</code> field on each
        stored statement records which path produced the values.
      </p>
    </section>
  );
}
